apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: app
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: 982389650543.dkr.ecr.us-west-2.amazonaws.com/ea-eks-kafka-producer:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"