apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: app
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: gcr.io/ea-k8s-381622/kafka-producer:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"