apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: app
spec:
  selector:
    app: kafka-consumer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP