apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: app
spec:
  selector:
    app: kafka-producer
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP