apiVersion: v1
kind: Service
metadata:
  name: mongodb-frontend-service
  namespace: app
spec:
  selector:
    app: mongodb-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer