FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/

COPY index.html /usr/src/app/
COPY script.js /usr/src/app/
COPY style.css /usr/share/nginx/html/

EXPOSE 81
