apiVersion: v1
kind: Service
metadata:
  name: mongodb-backend-service
  namespace: app
spec:
  selector:
    app: mongodb-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP