apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-backend
  namespace: app
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-backend
  template:
    metadata:
      labels:
        app: mongodb-backend
    spec:
      containers:
      - name: mongodb-backend
        image: gcr.io/ea-k8s-pro/ea-eks-mongodb-backend:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"