apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-frontend
  namespace: app
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-frontend
  template:
    metadata:
      labels:
        app: mongodb-frontend
    spec:
      containers:
      - name: mongodb-frontend
        image: gcr.io/ea-k8s-pro/ea-eks-mongodb-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"